---
- hosts: tag_Name_ECS_Instance___EC2ContainerService_prod
  remote_user: ec2-user
  become: true
  tasks:
    - name: Create folder for files
      file:
        path: /home/ec2-user/website
        state: directory
    - name: Send files
      copy:
        src: "{{playbook_dir}}/"
        dest: /home/ec2-user/website
    - name: Find container id and register output
      shell: docker ps -q -f "ancestor=mattrayner/lamp"
      register: container_id
    - name: Copy to docker container
      command: docker cp "/home/ec2-user/website/." {{container_id.stdout}}:/var/www/html
    - name: Restart docker container
      command: docker restart {{container_id.stdout}}
