// Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import java.util.*;
import java.net.MalformedURLException;
import java.net.URL;
public class TestRedirectTest {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  @Before
  public void setUp() {
    driver = new ChromeDriver();
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }
  @After
  public void tearDown() {
    driver.quit();
  }
  @Test
  public void testRedirect() {
    driver.get("http://127.0.0.1/");
    driver.manage().window().setSize(new Dimension(1936, 1056));
    assertThat(driver.getTitle(), is("RMIT Store"));
    driver.findElement(By.linkText("Clothing")).click();
    assertThat(driver.getTitle(), is("Official RMIT Apparel - RMIT Store"));
    driver.findElement(By.linkText("Accessories")).click();
    assertThat(driver.getTitle(), is("Accessories - RMIT Store"));
    driver.findElement(By.linkText("Stationery")).click();
    assertThat(driver.getTitle(), is("Stationery - RMIT Store"));
    driver.findElement(By.linkText("Course")).click();
    assertThat(driver.getTitle(), is("Course - RMIT Store"));
    driver.findElement(By.xpath("//a[contains(@href, \'https://www.campusstore.rmit.edu.au/collections/special-collection\')]")).click();
    assertThat(driver.getTitle(), is("Special Collection - RMIT Store"));
    driver.findElement(By.linkText("Sale")).click();
    assertThat(driver.getTitle(), is("Sale - RMIT Store"));
  }
}
